### ISSUE TITLE
建议tiup配置修改优化一下

### ISSUE THREAD

**Issue by LittleFall** [tidb-incubator/tide#20]
TiUP cluster 配置的时候，两个 diff 窗口都是可以编辑的，我第一次使用的时候改成了左边，导致没有生效。建议把左边设置为 readonly。
![image](https://user-images.githubusercontent.com/8433465/104828857-7ecc4b80-58a8-11eb-8172-e8424fdc47db.png)

**Comment by baurine** [comment]
Good suggestion!

**Comment by baurine** [comment]
It has no way to make the left side read-only, so we show a message box to tell the user that only the right side can be edited.

![image](https://user-images.githubusercontent.com/1284531/115150631-d5aa1280-a09b-11eb-96ee-fc5cb7b83744.png)

It is refined in PR #50

**Comment by baurine** [comment]
@LittleFall please try 0.3.2, thanks!

**Comment by LittleFall** [comment]
It works, thanks~
