### ISSUE TITLE
为什么Playground没有显示cluster呢？

### ISSUE THREAD

**Issue by SilvaXiang** [tidb-incubator/tide#34]
playground.toml配置文件如下：
![image](https://user-images.githubusercontent.com/22973642/106753149-3f527d00-6666-11eb-972f-5bed2207a7ca.png)
只有TiDB组建选择自己本地的二进制，但是cluster下没有集群的信息

**Comment by baurine** [comment]
![image](https://user-images.githubusercontent.com/1284531/106754014-6b223280-6667-11eb-9409-245788a75954.png)

把鼠标放到这个红框的地方，会出现一个刷新按钮，点一下那个刷新按钮试试呢？

本来设计是有自动刷新的，但只刷新几分钟。初次启动时间太长，超过了这个时间，就只能手动刷新了...

**Comment by SilvaXiang** [comment]
> ![image](https://user-images.githubusercontent.com/1284531/106754014-6b223280-6667-11eb-9409-245788a75954.png)
> 
> 把鼠标放到这个红框的地方，会出现一个刷新按钮，点一下那个刷新按钮试试呢？
> 
> 本来设计是有自动刷新的，但只刷新几分钟。初次启动时间太长，超过了这个时间，就只能手动刷新了...

这个就是刷新过的

**Comment by baurine** [comment]
OK，请问您用的是哪个 linux 发行版？我来测试一下。我们还没有在 linux 上测试过。

**Comment by SilvaXiang** [comment]
> OK，请问您用的是哪个 linux 发行版？我来测试一下。我们还没有在 linux 上测试过。

是CentOS Linux release 7.6，请问你们都是在Mac 上测试的嘛？最近也想在Mac本机上玩TiDB的，用PlayGround方式安装至少需要多大的存储呀

**Comment by baurine** [comment]
> > OK，请问您用的是哪个 linux 发行版？我来测试一下。我们还没有在 linux 上测试过。
> 
> 是CentOS Linux release 7.6，请问你们都是在Mac 上测试的嘛？最近也想在Mac本机上玩TiDB的，用PlayGround方式安装至少需要多大的存储呀

是的，我是指这个插件只在 mac 上测试了哈，实际底层是调用了 tiup 的命令。tiup 本身在 linux 上是测试过的。用 playground 安装需要的存储不大，几大组件的二进制包总共才 200M 左右。但如果你想调试开发的话，空间就要大多了，像 tikv 编译后在我 mac 上占了 20GB 的空间。我的 mac 选了 256GB 硬盘目前空间有些紧张了。

**Comment by SilvaXiang** [comment]
> > > OK，请问您用的是哪个 linux 发行版？我来测试一下。我们还没有在 linux 上测试过。
> > 
> > 
> > 是CentOS Linux release 7.6，请问你们都是在Mac 上测试的嘛？最近也想在Mac本机上玩TiDB的，用PlayGround方式安装至少需要多大的存储呀
> 
> 是的，我是指这个插件只在 mac 上测试了哈，实际底层是调用了 tiup 的命令。tiup 本身在 linux 上是测试过的。用 playground 安装需要的存储不大，几大组件的二进制包总共才 200M 左右。但如果你想调试开发的话，空间就要大多了，像 tikv 编译后在我 mac 上占了 20GB 的空间。我的 mac 选了 256GB 硬盘目前空间有些紧张了。

那请问我只编译TiDB组件，也就是说TiDB组件用本地编译的，大概需要多大空间呢？我的Mac太小了😂

**Comment by baurine** [comment]
我看了一下我 mac 上 tidb 项目编译后占了 512MB，不包括下载在 GOPATH 下面的那些包的大小。

```sh
> pwd
/Volumes/T7/Codes/trace-tidb/tidb                                                                             
> du -sh
512M	.
```

你可以考虑买个高速固态硬盘扩展一下磁盘空间，比如三星 T5/T7。

**Comment by dragonly** [comment]
@SilvaXiang 请问现在还有问题吗，有任何反馈可以提，没有的话这个issue就先关闭了哈，随时可以重新打开。
